#!/usr/local/bin/node

var program = require("commander");

program
	.version("0.0.4")
	.command("crawl", "Crawl WikiVet for quizzes")
	.command("convert", "Convert JSON to moodle XML")
	.parse(process.argv);